In [2]:
import numpy as np
arr1=np.array([2,3,4,5,6])
print(arr1)

[2 3 4 5 6]


In [5]:
arr2=np.array((2,3))
print(arr2)

[2 3]


In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(3) #it gives a identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
array1=np.arange(1,10,2)  #it gives a range from 1 to 10 with the addition of 2 in everyelement


NOW we check the properties of array


In [14]:
print(arr1.shape) #it tells the how many element in the array

(5,)


In [16]:
print(arr1.size)

5


In [18]:
arr=np.array([6,8,3,4],dtype=np.float32)
arr.dtype

dtype('float32')

In [20]:
int_arr=arr.astype(np.int32) #convert the data into 32bit integer data
int_arr.dtype

dtype('int32')

In [4]:
#its the practice of the numpy arr
arr3=np.array([[2,3,6],[9,7,4],[6,3,1,]])
print(arr3)

[[2 3 6]
 [9 7 4]
 [6 3 1]]


In [7]:
print(np.sum(arr3,axis=0))  #it give the  addition of the veritical rows

[17 13 11]


In [8]:
print(np.sum(arr3,axis=1))  #it give the  addition of the howrizintal rows

[11 20 10]
