In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [3]:
result=[]
for i in arr:
    result=arr*2
print(result)   #this is the simple loop operation

[ 2  4  6  8 10 12 14]


In [5]:
# now vectirozation
result=arr*2
print(result)

[ 2  4  6  8 10 12 14]


In [6]:
#broadcasting with two arrays
arr1=np.array([1,2,3])
arr2=np.array([10,20,30])
baddition=arr1+arr2
print(baddition)

[11 22 33]


In [9]:
#broadcating with 2d and 1d array
arr3=np.array([[1,2,3],[3,4,5,]])
arr4=np.array([3,6,9])
result=arr3+arr4
print(result)

[[ 4  8 12]
 [ 6 10 14]]


In [ ]:
=