In [2]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5],[7,8,9]])
print(arr1)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [6]:
print(np.sum(arr1, axis=0)) #

[11 14 17]


indexing and multidimenssion array


In [ ]:
arr2=np.array([[6,8,9,],[7,3,8],[7,3,4,]])
print(arr2)
print(arr2[0,1])  #it shows the element on rows and column 1 is that 8

[[6 8 9]
 [7 3 8]
 [7 3 4]]
8


In [11]:
print(arr2[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[8 9]
 [3 8]]


In [14]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])


print(arr3D.shape) #the output show that (depth=2,rows=2,column=3) 
print(arr3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
