In [8]:
import numpy as np
arr=np.array([[1,9,3],[4,3,4],[5,6,7]])
arr

array([[1, 9, 3],
       [4, 3, 4],
       [5, 6, 7]])

In [2]:
sum_arr=np.sum(arr,axis=0)
sum_arr  #it show the addition of the rows 

array([ 8, 11, 14])

In [9]:
print(arr[1][0])

4


In [15]:
print(arr[0:2,:3])

[[1 9 3]
 [4 3 4]]


The 3d array indexing and slicing
