In [3]:
import numpy as np
myarr=np.array([[1,2,3],[4,5,6]])
print(myarr)

[[1 2 3]
 [4 5 6]]


In [ ]:
flat=np.array(myarr.flatten())
print(flat)  #this function will convert the 2d array into 1d array

[1 2 3 4 5 6]


In [5]:
flat[0:3]

array([1, 2, 3])

In [7]:
new_array=flat[2:5] #this is slicing the array and creating a new array from the original array
print(new_array)

[3 4 5]


In [8]:
new_array[1]=66534
print(new_array)

[    3 66534     5]


In [ ]:
print(flat)  #why this happen beacuse the it not affect the original array because we have created a new array

[    1     2     3 66534     5     6]
